# _quarto-slides.yml
project:
  type: default
  execute-dir: file
  post-render:
    - powershell -ExecutionPolicy Bypass -File scripts/collect-rendered-slides.ps1
  render:
    - slides/loading-data.qmd
    - slides/pipe.qmd
    - slides/survey-data.qmd
    - slides/filter.qmd

execute:
  echo: true
  freeze: false


knitr:
  opts_chunk:
    echo: true

format: revealjs

# so referenced assets/bibliography work regardless of where slides live
bibliography: references.bib

author: "Prof. Dr. Nicolas Meseth"
lang: en


   
# powershell -ExecutionPolicy Bypass -File scripts/render-changed-slides.ps1

# powershell -ExecutionPolicy Bypass -File scripts/render-changed-slides.ps1 -Force

