# _quarto-slides.yml
project:
  type: default
  execute-dir: file
  post-render:
    - powershell -ExecutionPolicy Bypass -File scripts/collect-rendered-slides.ps1
  render:
    - r-basics/slides/loading-data-slides.qmd
    - r-basics/slides/pipe-slides.qmd
    #- project-1-survey/slides/survey-data-slides.qmd
    

execute:
  echo: true
  freeze: false


knitr:
  opts_chunk:
    echo: true

format:
  revealjs:
    slide-level: 2
    theme: dark
    embed-resources: true
    logo: ../../images/slides/hs_logo.svg
    slide-number: c/t
    highlight-style: atom-one
    code-line-numbers: false
    code-link: true

# so referenced assets/bibliography work regardless of where slides live
bibliography: references.bib

author: "Prof. Dr. Nicolas Meseth"
lang: en


   
