project:
  type: book
  execute-dir: project
  resources:
    - slides/**

lang: de

execute:
  warning: false
  message: false
  freeze: auto

book:
  title: "Hands-On Exploratory Data Analytics"
  author: "Nicolas Meseth"
  date: today
  date-format: long
  search: true
  output-file: "Hands-On-Exploratory-Data-Analytics-Book"
  #downloads: [pdf]


  chapters:
    - index.qmd

    - part: "Hintergründe"
      chapters:
      - 01-background/empirical-research.qmd

    - part: "Erste Schritte mit R"
      chapters:
      - 02-r-basics/ide.qmd
      - 02-r-basics/programming-with-r.qmd
      - 02-r-basics/data-representation.qmd

    - part: "Datentransformation"
      chapters:
      - 03-data-transformation/loading-data.qmd
      - 03-data-transformation/pipe.qmd
      - 03-data-transformation/exploring-data.qmd
      - 03-data-transformation/select.qmd
      - 03-data-transformation/mutate-modify.qmd
      - 03-data-transformation/mutate-add.qmd  
      - 03-data-transformation/filter.qmd
      - 03-data-transformation/summarize.qmd
      - 03-data-transformation/joining-data.qmd

    - part: "Datenvisualisierung"
      chapters:
      - 04-data-visualization/grammar-of-graphics.qmd
      - 04-data-visualization/bar-charts.qmd
      - 04-data-visualization/scatter-plots.qmd
      - 04-data-visualization/histograms.qmd
      - 04-data-visualization/boxplots.qmd
      - 04-data-visualization/line-charts.qmd
      - 04-data-visualization/visualizations-polish.qmd

    - part: "Projekt 1: Umfragen"
      chapters:
      - project-1-survey/survey-data.qmd
      - project-1-survey/types-of-variables.qmd
      

    - part: "Projekt 2: News"
      chapters:
      - project-2-news/load.qmd
      - project-2-news/factors.qmd
      - project-2-news/variables.qmd
      - project-2-news/time.qmd


      
    - appendix/appendix-a-scraping.qmd
    - appendix/appendix-b-supplemental.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles/sidebar.css
    theme:
      - cosmo
      - brand
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    number-depth: 2
    code-annotations: hover
    code-line-numbers: false
    code-link: true
    linkcolor: "#009ee3"
